### ISSUE TITLE
Qua-server: student news-feed

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-kit#11]
PROJECTS: qua-server
CHANGESET: Add a complex component to our yesod site
DESCRIPTION:

The framework contains two exercises for edX students:
 * Design exercise: students are asked to submit their own designs via `qua-view`.
 * Vote exercise: students vote on pairs of designs "better-worse".

Also students are allowed to comment and like-dislike the submissions. In order to encourage students to work on their designs, we want to make a news-feed on the main page. The personalized news-feed for a student contains:
 * Likes-dislikes + comments regarding the student's design submission
 * Worse-better comparisons with links to paired submissions and corresponding comments
 * Design updates for the designs that were previously commented by the user
 * Some other metrics and updates related to the designs of other (somehow related) students

Note, each students produces at least 10-20 worse-better comparisons (most of them without comments), so this type of feedback should be somehow nicely grouped.

Also we can think of some ways to notify students about updates / integration with social networks.

**Comment by mb21** [comment]
- [x] only for students
- [x] blue box -> my most recent submission
- [ ] news feeds with:
    - [x] expert comment (`expert_review` table)
    - [x] user comments on design (`review` table)
    - [x] comparison vote comment (`vote` table)
