### ISSUE TITLE
Qua-server: edX exercise import

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-kit#15]
PROJECTS: qua-server
CHANGESET: working with filesystem + database + a little bit of yesod
DESCRIPTION:

The exercise consists of a geometry file and design criteria descriptions/icons/images. Currently, importing of exercise files into the database is hardcoded in [`Application/SetupProblemData`](https://github.com/achirkin/qua-kit/blob/master/apps/hs/qua-server/src/Application/SetupProblemData.hs). We need to design a better way of doing this.

One, the easiest option is to define a folder structure, so that qua-server looks into the folders once in a while (at least at startup), and imports new data as it comes.

Another option is to provide an admin page to allow creating new exercises by hand.

**Comment by NorfairKing** [comment]
I think this is done now?

**Comment by achirkin** [comment]
Yep, closing it
