### ISSUE TITLE
Qua-server: reviews from experts

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-kit#19]
PROJECTS: qua-server
CHANGESET: several yesod handlers + DB entities
DESCRIPTION:

We need to add an option to write design reviews from experts.
This includes:
  * Add new [`UserRole`](https://github.com/achirkin/qua-kit/blob/master/apps/hs/qua-server/src/Model/CustomTypes.hs) - "expert"
  * Add a DB table to keep reviews: submission id + text + single grade (not per-criterion)
  * Add a page to write a review on a design
  * Visualize reviews on design view pages
  * Add an indicator of a number of reviews and the average grade into the gallery

Later we also need to add a way to notify reviewers that some design submissions are undervoted for a while. Also add an admin option to invite new reviewers #16 . And add review notification to a user news-feed #11 .

**Comment by achirkin** [comment]
A few small things (not urgent) regarding the current state of email authorization:
  * Need to make sure that user is redirected to the main page after login/register/verify (`@MoocHomeR`).
  * Use `setMessage` to show info messages if necessary
  * Change register button to link to make sure users do not perceive login form as registration form
  * If user is logged in via LDAP or edX, allow to register with email to bind two accounts together.

**Comment by achirkin** [comment]
Also my "Setup local account" widget still appears on the main page even if I logged in with email.

**Comment by mb21** [comment]
still oustanding:

- If user is logged in via LDAP or edX, allow to register with email to bind two accounts together.

**Comment by achirkin** [comment]
So far works great! A few things to finalize this:
 * Add mouseover style hand when you click on stars
 * Make review require some amount of text, so that experts have to explain their grades :) let say, at least 80 characters
 * Add the grade mark in the gallery (e.g. together with criteria values)
 * Change "view" to a red REVIEW button for the submissions that don't get enough votes and don't have a grade (should only affect experts)

**Comment by mb21** [comment]
I think those are all addressed now, still outstanding though:

> If user is logged in via LDAP or edX, allow to register with email to bind two accounts together.

**Comment by achirkin** [comment]
Another small thing missing: "back" button on https://qua-kit.ethz.ch/admin/request-review page, similar to one e.g. in https://qua-kit.ethz.ch/admin/criterion-editor
