### ISSUE TITLE
Issues with worskop mode in qua-kit

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-kit#52]
Syd:

* [x] Scenario invitation link makes user UR_NOBODY, but should make them UR_STUDENT
* [ ] If this email already registered, then just ask him for password and re-assign to the new scenario_problem_id
* [x] add temporary user ("no, I don't want to enter email, just allow me to work on a scenario this time") (at intersection between Syd and Mauros stuff)
* [ ] geometry scale: 1. make it optional, but allow user to set it. If it is omitted, make sure this parameter is not passed to the viewer
* [x] When registering, redirect to the viewer instead of to a page that says your need to check your email.

Mauro:

* [x] add another link to gallery to filter explicitly by scenario_problem id (get parameter `exercise_id`).
* [x] If user used email verification, but did not set password, then he cannot re-use the link to set password

**Comment by achirkin** [comment]
* add another link to gallery to filter explicitly by scenario id.
* add temporary user ("no, I don't want to enter email, just allow me to work on a scenario this time")

**Comment by NorfairKing** [comment]
In `src/Foundation.hs`, line 479 in `maybeEnroll`, we can have a look at setting the role in the session as well.

**Comment by NorfairKing** [comment]
Working on this in https://github.com/NorfairKing/qua-kit/tree/workshop-mode

**Comment by achirkin** [comment]
Closing, because remaining issues are obsolete or went to #75 .
