### ISSUE TITLE
The buildings don't move

### ISSUE THREAD

**Issue by Vivinha** [achirkin/qua-kit#81]
I'm doing the course Smart City at EDX. I followed the instructions inthe exerciwse at Moduloe 2, but the buildings don't move. They turn red, but I cannot move them without move all the image. I tried in different computers and all the same.
What can I do?
I must finish the course.
Thanks 

Viviane

**Comment by achirkin** [comment]
Hi @Vivinha! Thanks for the report.  Could you please tell me which browsers did you use?

**Comment by Vivinha** [comment]
Hi.
I have used Google Chrome. Is it better another one?

2018-04-23 13:13 GMT-03:00 Artem M. Chirkin <notifications@github.com>:

**Comment by achirkin** [comment]
Hmm, so I think I found you in the logs, you tried to use it several times between 2018-04-16 and 2018-04-23, right?

I could not find anything wrong in the logs, except that you indeed did not move any objects.

Could you please tell my which version of OS you use, and, possibly, version of Google Chrome you use (as it is written in `Menu -> Help -> About Google Chrome`)?
I will try to figure out what is the problem.
In the meanwhile, if you need to finish the exercise quickly, you can try to use Firefox or Safari or MS Edge...

**Comment by Vivinha** [comment]
Sorry the delay to answer you,

I tried in two differents computer

One,  it's windows 7 and Google Chrome  Version 66.0.3359.117  64 bits.

The other, it's windows 10 and Google Chrome Version  64.0.3282.186  64 bits

I tried Firefox and the same problem. I didn' try MS Edge.

If windows 10 is better than 7, I can use only the first one.

Thanks

2018-04-24 12:01 GMT-03:00 Artem M. Chirkin <notifications@github.com>:

**Comment by Vivinha** [comment]
Good Morning Artem,

Today I tryed again and the green/yellow blocks moved and turned, but de
gray ones doesn't. This happend inGoogle Chrome and Firefox, the same thing.
They gray blocks must move, don't they?

2018-04-24 12:01 GMT-03:00 Artem M. Chirkin <notifications@github.com>:

**Comment by achirkin** [comment]
No, gray buildings are static buildings usually, You are not supposed to move them.

**Comment by Vivinha** [comment]
Só, I think the problem is solved. I did the exercice todas. Tank you for
tour help

Em sex, 4 de mai de 2018 12:33, Artem M. Chirkin <notifications@github.com>
escreveu:

**Comment by achirkin** [comment]
Ok, great! Then I'm closing the issue. I will tell our teaching team to emphasize more clearly that students are not supposed to move grey (static) buildings.
