### ISSUE TITLE
I CAN'T SUBMIT MY DESIGN

### ISSUE THREAD

**Issue by ethchiarape** [achirkin/qua-kit#83]
Hello, 
I developed my design for Singapore (I subscribed following this link: https://goo.gl/fQtmEP and then started the design).
I am using Safari as a browser and I could not rotate the buildings but anyway I came to an end and wanted to submit the design but there was and error. I saved the design, but now, if I upload it, there isn't anymore the 'submit' button.
What should I do?

Thank you

**Comment by achirkin** [comment]
Hi,

Do you remember the error message?

You say you saved the design; you mean -- saved the geometry to a file?
If yes, then send the email address you used to login at `qua-kit.ethz.ch` and the file you saved to my email address: chirkin [at] arch.ethz.ch. I will upload it to your profile and fix the submitting problem.
