### ISSUE TITLE
Qua-server: refactor user session representation and functionality

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-kit#9]
PROJECTS: qua-server
CHANGESET: Learning to work with yesod sessions
DESCRIPTION:

Function [`setupEdxParams`](https://github.com/achirkin/qua-kit/blob/master/apps/hs/qua-server/src/Foundation.hs#L285) is used to set up most of session parameters; parts of code related to authentication are in the same file near `YesodAuth` instance. All of these are hard to read and understand. I propose to create a special data type for server-side representation of the client user session. It can reside in another module, let say `Model/Session.hs`.

Assuming `data UserSession = ...`, the data type should:
  * Contain [`UserRole`](https://github.com/achirkin/qua-kit/blob/master/apps/hs/qua-server/src/Model/CustomTypes.hs)
  * Maybe contain `UserId`?
  * Have all parameters related to edX authentication if `UR_STUDENT`
  * Show nice custom error messages if some of the session keys missing
  * Provide information about the way user has been authenticated (local/ldap/edX)
  * I think, the interface better be lazy to avoid unnecessary session lookups?

**Comment by NorfairKing** [comment]
I started work on this in #31, but it's not exactly what you were describing. Please let me know what you think.

**Comment by achirkin** [comment]
That's good! Just add DB requests as we discussed in telegram

**Comment by NorfairKing** [comment]
Has this been completed?

**Comment by achirkin** [comment]
Isn't your lensy functions in Model.Session? :)

**Comment by NorfairKing** [comment]
Oh yeah, that's done. Cool!
